// crudFront/src/views/Home.jsx
import React, { useState, useEffect } from "react";
import Header from "../components/static/Header";
import "../styles/main.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { useNavigate } from 'react-router-dom';
import { getAllUsers, deleteUser } from "../services/api";
import { formatDate } from "../utils/DateUtils";

export default function Home() {
    const [customers, setCustomers] = useState([]);
    const [reloadFlag, setReloadFlag] = useState(false);
    const navigate = useNavigate();

    const handleRegister = () => {
        navigate("/customer/new");
    };

    const handleEdit = (user) => {
        navigate("/customer/update", { state: { user } });
    };
    
    const deleteUsers = async (id) => {
        try {
            const response = await deleteUser(id);
           
            if(response && response.type === "SUCCESS") {
                // Actualiza el estado local filtrando el usuario eliminado
                setCustomers(prevCustomers => prevCustomers.filter(user => user.id !== id));
            }
        } catch(error) {
            console.error("Delete error:", error);
            // Opcional: Mostrar mensaje de error al usuario
        }
    };
    
    const loadUsers = async () => {
        try {
            setCustomers(await getAllUsers());
        } catch (error) {
            console.log(error);
        }
    };

    useEffect(() => {
        loadUsers();
    }, [reloadFlag]);

    return (
        <div className="app-container">
            <Header />
            <div className="content">
                <div className="add-button-container">
                    <button className="btn btn-outline-success" onClick={handleRegister}>Agregar nuevo</button>
                </div>
                <table className="table table-container">
                    <thead className="table-dark">
                        <tr>
                            <th>ID cliente</th>
                            <th>Nombre completo</th>
                            <th>CURP</th>
                            <th>Fecha de nacimiento</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {customers.map((user) => (
                            <tr key={user.id}>
                                <td>{user.id}</td>
                                <td>{user.name} {user.lastName}</td>
                                <td>{user.curp}</td>
                                <td>{formatDate(user.birthDate)}</td>
                                <td>
                                    <div className="actions-container">
                                        <button className="btn btn-outline-warning" onClick={() => handleEdit(user)}>Editar</button>
                                        <button 
                                            className="btn btn-outline-danger" 
                                            onClick={() => deleteUsers(user.id)} 
                                        >
                                            Eliminar
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
}

// vueCrud/src/views/Home.vue
<template>
    <div class="app-container d-flex flex-column align-items-center">
        <Header />
        <div class="d-flex justify-content-between align-items-center p-4 w-100">
            <div class="text-center flex-grow-1">
                <h2>Lista de clientes</h2>
            </div>
            <div>
                <button class="btn btn-success" @click="handleNewCustomer">Registrar nuevo</button>
            </div>
        </div>

        <div class="col-8">
            <table class="table">
                <thead class="table-dark">
                    <tr>
                        <td>ID</td>
                        <td>Nombre</td>
                        <td>Curp</td>
                        <td>Fecha de nacimiento</td>
                        <td>Acciones</td>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="cliente in clientes" :key="cliente.id">
                        <td>{{ cliente.id }}</td>
                        <td>{{ cliente.name }} {{cliente.lastName}}</td>
                        <td>{{ cliente.curp }}</td>
                        <td>{{ formatDate(cliente.birthDate) }}</td>
                        <td>
                            <div class="action-container">
                                <button class="bt  bt-warning">Editar</button>
                                <button class="bt bt-danger">Eliminar</button>
                            </div>

                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</template>

<script>
import Header from '../components/Header.vue';
import { getAllUsers } from '../services/api.js';
import { formatDate } from '../utils/DateUtils.js';

export default {
    methods: {
    formatDate,
    handleNewCustomer() {
    this.$router.push('/newCustomer');
  } },
    components: {
        Header
    },
    data() {
        return {
            clientes: [],
        };
    },
    async mounted() {
        try {
            this.clientes = await getAllUsers();
        } catch (error) {
            console.error(error.message);
            alert('Error al cargar clientes: ' + error.message);
        }
    }
};
</script>
